### ISSUE TITLE
Upgrade to Bootstrap 4

### ISSUE THREAD

**Issue by mtugnoli** [tommcclean/PortalCMS#56]
I see the previous issue on 7 Sep 2016 with same question.

Do you think will be developed ?

**Comment by tommcclean** [comment]
I did look into upgrading to Bootstrap 4 previously, but there are a few breaking changes across the board that would be difficult to migrate. Given the nature of the way the admin can manipulate the HTML freely, the difficult element would be migrating existing code forwards. So its not something I am actively looking into upgrading, but may take another look in future.
