### ISSUE TITLE
How to connect the SQL database.

### ISSUE THREAD

**Issue by Ertuit** [tommcclean/PortalCMS#60]
Hello,
I'm a noob and I really want to install your cms on my server.
I have install Visual Studio 2015 and SQL server express 2019 and try to connect the database but I don't know how to do it (and obviously when I try even different possibility it fail...).
Have you a tutorial ?
I know how to do that on linux with mariadb and wordpress for exemple but on windows I am completely lost.
Thank you very much.
Sorry for the inconvenience.
Ertuit.

**Comment by sohailqureshi** [comment]
If you're running on local host and the SQL server is on your locals host as well then you should simply be able to compile and run the Visual Studio project (press F5)

**Comment by Ertuit** [comment]
Oh, thank you. It work now !
I'm so happy. :)
